services:
  lsky-pro:
    container_name: lsky-pro
    image: dko0/lsky-pro
    restart: always
    volumes:
      - ./data/html:/var/www/html
    ports:
      - 7791:80
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=<DB_NAME>
      - MYSQL_USER=<USERNAME>
      - MYSQL_PASSWORD=<PASSWORD>

  mysql:
    image: mysql:8.0
    container_name: lsky-pro-db # sql address
    restart: always
    environment:
      - MYSQL_DATABASE=<DB_NAME>
      - MYSQL_USER=<USERNAME>
      - MYSQL_PASSWORD=<PASSWORD>
      - MYSQL_ROOT_PASSWORD=<ROOT_PASSWORD>
    volumes:
      - ./data/db:/var/lib/mysql
