services:
  webdav:
    container_name: webdav
    image: bytemark/webdav
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      USERNAME: <USERNAME>
      PASSWORD: <PASSWORD>
    volumes:
      - ./data:/var/lib/dav/data
