# Auto-generated using compose2nix v0.3.2-pre.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."vote-postgres" = {
    image = "bitnami/postgresql:latest";
    environment = {
      "POSTGRES_DB" = "polls";
      "POSTGRES_PASSWORD" = "docker";
      "POSTGRES_USER" = "docker";
    };
    volumes = [
      "vote_polls_pg_data:/bitnami/postgresql:rw"
    ];
    ports = [
      "5432:5432/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=postgres"
      "--network=vote_default"
    ];
  };
  systemd.services."docker-vote-postgres" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-vote_default.service"
      "docker-volume-vote_polls_pg_data.service"
    ];
    requires = [
      "docker-network-vote_default.service"
      "docker-volume-vote_polls_pg_data.service"
    ];
    partOf = [
      "docker-compose-vote-root.target"
    ];
    wantedBy = [
      "docker-compose-vote-root.target"
    ];
  };
  virtualisation.oci-containers.containers."vote-redis" = {
    image = "bitnami/redis:latest";
    environment = {
      "ALLOW_EMPTY_PASSWORD" = "yes";
    };
    volumes = [
      "vote_polls_redis_data:/bitnami/redis/data:rw"
    ];
    ports = [
      "6379:6379/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=redis"
      "--network=vote_default"
    ];
  };
  systemd.services."docker-vote-redis" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-vote_default.service"
      "docker-volume-vote_polls_redis_data.service"
    ];
    requires = [
      "docker-network-vote_default.service"
      "docker-volume-vote_polls_redis_data.service"
    ];
    partOf = [
      "docker-compose-vote-root.target"
    ];
    wantedBy = [
      "docker-compose-vote-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-vote_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f vote_default";
    };
    script = ''
      docker network inspect vote_default || docker network create vote_default
    '';
    partOf = [ "docker-compose-vote-root.target" ];
    wantedBy = [ "docker-compose-vote-root.target" ];
  };

  # Volumes
  systemd.services."docker-volume-vote_polls_pg_data" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect vote_polls_pg_data || docker volume create vote_polls_pg_data
    '';
    partOf = [ "docker-compose-vote-root.target" ];
    wantedBy = [ "docker-compose-vote-root.target" ];
  };
  systemd.services."docker-volume-vote_polls_redis_data" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect vote_polls_redis_data || docker volume create vote_polls_redis_data
    '';
    partOf = [ "docker-compose-vote-root.target" ];
    wantedBy = [ "docker-compose-vote-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-vote-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
